### ISSUE TITLE
JsonSyntaxException for "category" fields

### ISSUE THREAD

**Issue by barissaglam** [ARTLabs-Engineering/Meshkraft-Android#5]
When I start session with SKU, I get this error. com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 1 column 59 path $.category

Expected `category` type is **String**: 
![Screen Shot 2022-01-20 at 11 29 19](https://user-images.githubusercontent.com/13089444/150301581-fe2949f3-149d-4ebd-bb62-d7c6bf491148.png)

but `category` type is **Object** in response 
![Screen Shot 2022-01-20 at 11 25 45](https://user-images.githubusercontent.com/13089444/150301084-69705b54-fe67-42fb-bad5-bac49d4837eb.png)

.

**Comment by sercanov** [comment]
@barissaglam thanks for the heads up. Recently we changed our JSON structure in API response. This SDK doesn't actually use `category` field. It needs to be deleted to avoid the exception. Will try to fix it today. You can also create a PR if you like :)
