### ISSUE TITLE
README.md typo issue

### ISSUE THREAD

**Issue by yagmurerdogan** [ARTLabs-Engineering/Meshkraft-Android#6]
### 👉🏻 In **"Usage"** section;
It says `Mashkraft.setApiKey("TOKEN")` but It should be `Meshkraft` instead of `Mashkraft`
<img width="873" alt="Screen Shot 2022-01-20 at 14 38 10" src="https://user-images.githubusercontent.com/47380312/150332426-2266b82f-833e-466f-afa2-2b83b5b9c0f7.png">
### 👉🏻 In **"AR Session"** section;
There are two different typos in this section.
Firstly, it says `Meshkraft.startArSession(context,"PRODUCT_SKU")` but it should be `startARSession` instead of `startArSession`
Finally, `MeshKraft.apply{...}` should be `Meshkraft` instead of `MeshKraft`
<img width="870" alt="Screen Shot 2022-01-20 at 14 38 29" src="https://user-images.githubusercontent.com/47380312/150332841-a46ea74c-b2e9-4789-96d7-8f80dd1e0f98.png">

**If you are open to contributions, you can assign this issue to me, thank you 🙏🏻**

**Comment by sercanov** [comment]
Thank you Yagmur. We're so open to contributions. I'd be happy to merge if you could open a PR :))

**Comment by yagmurerdogan** [comment]
Hi @sercanov,I just sent PR 🥳 Can you check it? https://github.com/ARTLabs-Engineering/Meshkraft-Android/pull/7 Thank you 🙏🏻
